export const UserActionTypes={
    SET_CURRENT_USER:"SET_CURRENT_USER",
    SET_CURRENT_USER_POSTS:"SET_CURRENT_USER_POSTS",
    SET_POSTS_TABLE_ROWS:"SET_POSTS_TABLE_ROWS",
    SET_POSTS_TABLE_HEADER:"SET_POSTS_TABLE_HEADER"
}